### ISSUE TITLE
Multiple copies of sample codes are downloaded if they are referred from multiple sessions.

### ISSUE THREAD

**Issue by Kiran-B** [ohoachuck/wwdc-downloader#24] opened 2015-06-15 05:18 UTC
Sample codes are being prefixed with their corresponding session IDs. While this is great to easily locate the same. it causes the script to download the same sample code multiple times.

Ex:  The sample code titled 'DemoBots: Building a Cross Platform Game with SpriteKit and GameplayKit' is being downloaded 5 times. 

As the above sample code is about 120 MB, it results in consuming additional bandwidth and time.

Possible solutions:
Easy : Don't rename the file.
Better : Detect the previous download and create an alias for the same.

**Comment by ohoachuck** [comment] 2015-06-18 00:57
Hello Kiran, 
Thank you for pointing out the issue. I was busy at the office back from WWDC and did not even see the few issues people have pointed since then  ;(
I had to scrash my head  tonight ( ;() ) to find the way to alias already downloaded Sample codes. I finally succeed (hope there is no regression). I have just committed the fix.

Thanx again for notify.

**Closed by ohoachuck** 2015-06-18 00:57 UTC
